// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IEquatable
{
	boolean equals(java.lang.Object to);
	
}


