// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.crypto.padding;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class NoPadding extends haxe.lang.HxObject
{
	public NoPadding(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public NoPadding()
	{
		//line 5 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NoPadding.hx"
		haxe.crypto.padding.NoPadding.__hx_ctor_haxe_crypto_padding_NoPadding(this);
	}
	
	
	protected static void __hx_ctor_haxe_crypto_padding_NoPadding(haxe.crypto.padding.NoPadding __hx_this)
	{
	}
	
	
	public static haxe.io.Bytes pad(haxe.io.Bytes ciphertext, int blockSize)
	{
		//line 9 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NoPadding.hx"
		return ciphertext.sub(0, ciphertext.length);
	}
	
	
	public static haxe.io.Bytes unpad(haxe.io.Bytes encrypt)
	{
		//line 14 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NoPadding.hx"
		return encrypt;
	}
	
	
}


