// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.crypto.padding;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class NullPadding extends haxe.lang.HxObject
{
	public NullPadding(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public NullPadding()
	{
		//line 6 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		haxe.crypto.padding.NullPadding.__hx_ctor_haxe_crypto_padding_NullPadding(this);
	}
	
	
	protected static void __hx_ctor_haxe_crypto_padding_NullPadding(haxe.crypto.padding.NullPadding __hx_this)
	{
	}
	
	
	public static haxe.io.Bytes pad(haxe.io.Bytes ciphertext, int blockSize)
	{
		//line 9 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		try 
		{
			//line 10 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			haxe.io.BytesBuffer buffer = new haxe.io.BytesBuffer();
			//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			{
				//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				int len = ciphertext.length;
				//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				if (( ( len < 0 ) || ( len > ciphertext.length ) )) 
				{
					//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
					throw haxe.lang.HaxeException.wrap(haxe.io.Error.OutsideBounds);
				}
				
				//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				buffer.b.write(((byte[]) (ciphertext.b) ), ((int) (0) ), ((int) (len) ));
			}
			
			//line 12 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			int padding = ( blockSize - ( ciphertext.length % blockSize ) );
			//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			{
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				int _g = 0;
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				int _g1 = padding;
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
				while (( _g < _g1 ))
				{
					//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
					int i = _g++;
					//line 14 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
					buffer.b.write(((int) (0) ));
				}
				
			}
			
			//line 16 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			return buffer.getBytes();
		}
		catch (java.lang.Throwable typedException)
		{
			//line 8 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	public static haxe.io.Bytes unpad(haxe.io.Bytes encrypt)
	{
		//line 21 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		int padding = 0;
		//line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		int pos = encrypt.length;
		//line 23 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		while (( ( padding == 0 ) && ( pos > 0 ) ))
		{
			//line 24 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			 -- pos;
			//line 25 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
			padding = ( encrypt.b[pos] & 255 );
		}
		
		//line 27 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\NullPadding.hx"
		return encrypt.sub(0, ( pos + 1 ));
	}
	
	
}


