// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.crypto.padding;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class TBC extends haxe.lang.HxObject
{
	public TBC(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public TBC()
	{
		//line 6 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		haxe.crypto.padding.TBC.__hx_ctor_haxe_crypto_padding_TBC(this);
	}
	
	
	protected static void __hx_ctor_haxe_crypto_padding_TBC(haxe.crypto.padding.TBC __hx_this)
	{
	}
	
	
	public static haxe.io.Bytes pad(haxe.io.Bytes ciphertext, int blockSize)
	{
		//line 9 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		try 
		{
			//line 10 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			int tb = ( ( ciphertext.b[( ciphertext.length - 1 )] & 255 ) & 1 );
			//line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			int paddingByte = ( (( tb == 1 )) ? (0) : (255) );
			//line 12 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			haxe.io.BytesBuffer buffer = new haxe.io.BytesBuffer();
			//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			{
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				int len = ciphertext.length;
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				if (( ( len < 0 ) || ( len > ciphertext.length ) )) 
				{
					//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
					throw haxe.lang.HaxeException.wrap(haxe.io.Error.OutsideBounds);
				}
				
				//line 13 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				buffer.b.write(((byte[]) (ciphertext.b) ), ((int) (0) ), ((int) (len) ));
			}
			
			//line 14 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			int padding = ( blockSize - ( ciphertext.length % blockSize ) );
			//line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			{
				//line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				int _g = 0;
				//line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				int _g1 = padding;
				//line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
				while (( _g < _g1 ))
				{
					//line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
					int i = _g++;
					//line 16 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
					buffer.b.write(((int) (paddingByte) ));
				}
				
			}
			
			//line 18 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			return buffer.getBytes();
		}
		catch (java.lang.Throwable typedException)
		{
			//line 8 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			throw haxe.lang.HaxeException.wrap(typedException);
		}
		
		
	}
	
	
	public static haxe.io.Bytes unpad(haxe.io.Bytes encrypt)
	{
		//line 23 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		int pos = ( encrypt.length - 1 );
		//line 24 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		int paddingByte = ( encrypt.b[pos] & 255 );
		//line 25 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		int padding = paddingByte;
		//line 26 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		while (( ( padding == paddingByte ) && ( pos > -1 ) ))
		{
			//line 27 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			 -- pos;
			//line 28 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
			padding = ( encrypt.b[pos] & 255 );
		}
		
		//line 30 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\padding\\TBC.hx"
		return encrypt.sub(0, ( pos + 1 ));
	}
	
	
}


