// Generated by Haxe 4.0.0-rc.5+b1fb4afca
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Date.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/StringBuf.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Type.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/db/Sqlite.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/io/File.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/io/FileOutput.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/thread/Lock.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/sys/thread/Mutex.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/EntryPoint.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/MainLoop.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/ds/List.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/format/JsonPrinter.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Output.hx",
"Permutation.hx",
"TestSqlite.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\?",
"C:\\HaxeToolkit\\haxe\\std\\StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Date.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\StringBuf.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Type.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\db\\Sqlite.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\io\\File.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\io\\FileOutput.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\thread\\Lock.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\sys\\thread\\Mutex.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\EntryPoint.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\MainLoop.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\List.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\format\\JsonPrinter.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Output.hx",
"D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\Permutation.hx",
"D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\TestSqlite.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Date",
"Permutation",
"Reflect",
"Std",
"StringBuf",
"StringTools",
"CustomTrace",
"TestSqlite",
"Type",
"sys.thread.Mutex",
"sys.thread.Lock",
"haxe.EntryPoint",
"haxe.Log",
"haxe.MainEvent",
"haxe.MainLoop",
"haxe.ds.List",
"haxe.ds._List.ListNode",
"haxe.ds.StringMap",
"haxe.format.JsonPrinter",
"haxe.io.Bytes",
"haxe.io.Output",
"sys.db._Sqlite.SqliteConnection",
"sys.db._Sqlite.SqliteResultSet",
"sys.db.Sqlite",
"sys.io.File",
"sys.io.FileOutput",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
