// Generated by Haxe 4.1.0-rc.1+0d88c583b
#include <hxcpp.h>

#include <stdio.h>

extern "C" void __hxcpp_main();

extern "C" void __hxcpp_lib_main();

#ifndef INCLUDED_TestSqlite
#include <TestSqlite.h>
#endif
#ifndef INCLUDED_haxe_EntryPoint
#include <haxe/EntryPoint.h>
#endif
HX_LOCAL_STACK_FRAME(_hx_pos_fe66fde75063e1fc_1___hxcpp_main,"hxcpp","__hxcpp_main",0x10478780,"hxcpp.__hxcpp_main","?",1,0x0000003f)



#include <hx/HxcppMain.h>

void __hxcpp_main() {
{
            	HX_STACKFRAME(&_hx_pos_fe66fde75063e1fc_1___hxcpp_main)
HXDLIN(   1)		::TestSqlite_obj::main();
HXDLIN(   1)		::haxe::EntryPoint_obj::run();
            	}
	}

void __hxcpp_lib_main() {
	HX_TOP_OF_STACK
	hx::Boot();
	__boot_all();
	__hxcpp_main();
	}
