// Generated by Haxe 4.1.0-rc.1+0d88c583b
#include <hxcpp.h>

namespace hx {
}

hx::Resource __Resources[] = {
	{ ::String(null()),0,0 }
};

namespace hx { Resource *GetResources() { return __Resources; } }
