// Generated by Haxe 4.0.0-rc.5+b1fb4afca
#include <hxcpp.h>

namespace hx {
}

hx::Resource __Resources[] = {
	{ ::String(null()),0,0 }
};

namespace hx { Resource *GetResources() { return __Resources; } }
