// Generated by Haxe 4.0.0-rc.5+b1fb4afca
#ifndef INCLUDED_CustomTrace
#define INCLUDED_CustomTrace

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(CustomTrace)



class HXCPP_CLASS_ATTRIBUTES CustomTrace_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef CustomTrace_obj OBJ_;
		CustomTrace_obj();

	public:
		enum { _hx_ClassId = 0x3e555f10 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="CustomTrace")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"CustomTrace"); }

		inline static hx::ObjectPtr< CustomTrace_obj > __new() {
			hx::ObjectPtr< CustomTrace_obj > __this = new CustomTrace_obj();
			__this->__construct();
			return __this;
		}

		inline static hx::ObjectPtr< CustomTrace_obj > __alloc(hx::Ctx *_hx_ctx) {
			CustomTrace_obj *__this = (CustomTrace_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(CustomTrace_obj), false, "CustomTrace"));
			*(void **)__this = CustomTrace_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~CustomTrace_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CustomTrace",f4,8c,8e,8f); }

		static void init();
		static ::Dynamic init_dyn();

};


#endif /* INCLUDED_CustomTrace */ 
