// Generated by Haxe 4.1.0-rc.1+0d88c583b
#ifndef INCLUDED_Permutation
#define INCLUDED_Permutation

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_fdce4ab2ba739b62_13_new)
HX_DECLARE_CLASS0(Permutation)



class HXCPP_CLASS_ATTRIBUTES Permutation_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Permutation_obj OBJ_;
		Permutation_obj();

	public:
		enum { _hx_ClassId = 0x53fc011e };

		void __construct(::Array< int > arr, ::Dynamic callBack,::Array< ::Dynamic> result);
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Permutation")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"Permutation"); }

		inline static hx::ObjectPtr< Permutation_obj > __new(::Array< int > arr, ::Dynamic callBack,::Array< ::Dynamic> result) {
			hx::ObjectPtr< Permutation_obj > __this = new Permutation_obj();
			__this->__construct(arr,callBack,result);
			return __this;
		}

		inline static hx::ObjectPtr< Permutation_obj > __alloc(hx::Ctx *_hx_ctx,::Array< int > arr, ::Dynamic callBack,::Array< ::Dynamic> result) {
			Permutation_obj *__this = (Permutation_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(Permutation_obj), false, "Permutation"));
			*(void **)__this = Permutation_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_fdce4ab2ba739b62_13_new)
HXLINE(  14)		int i = arr->length;
HXLINE(  15)		int total = 1;
HXLINE(  16)		while((i > 0)){
HXLINE(  17)			total = (total * i);
HXLINE(  18)			i = (i - 1);
            		}
HXLINE(  21)		::Permutation_obj::heapPermutation(arr,arr->length,total,callBack,result);
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Permutation_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Permutation",e6,5c,6e,f6); }

		static void heapPermutation(::Array< int > a,int size,int total, ::Dynamic callBack,::Array< ::Dynamic> result);
		static ::Dynamic heapPermutation_dyn();

};


#endif /* INCLUDED_Permutation */ 
