// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.java;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Init extends haxe.lang.HxObject
{
	public Init(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Init()
	{
		//line 24 "C:\\HaxeToolkit\\haxe\\std\\java\\Init.hx"
		haxe.java.Init.__hx_ctor_haxe_java_Init(this);
	}
	
	
	protected static void __hx_ctor_haxe_java_Init(haxe.java.Init __hx_this)
	{
	}
	
	
	public static void init()
	{
		//line 26 "C:\\HaxeToolkit\\haxe\\std\\java\\Init.hx"
		try 
		{
			//line 27 "C:\\HaxeToolkit\\haxe\\std\\java\\Init.hx"
			java.lang.System.setOut(((java.io.PrintStream) (new java.io.PrintStream(java.lang.System.out, true, "utf-8")) ));
			//line 28 "C:\\HaxeToolkit\\haxe\\std\\java\\Init.hx"
			java.lang.System.setErr(((java.io.PrintStream) (new java.io.PrintStream(java.lang.System.err, true, "utf-8")) ));
		}
		catch (java.io.UnsupportedEncodingException e)
		{
			//line 29 "C:\\HaxeToolkit\\haxe\\std\\java\\Init.hx"
			haxe.lang.Exceptions.setException(e);
		}
		
		
	}
	
	
}


