// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class AES_Test extends haxe.lang.HxObject
{
	public AES_Test(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public AES_Test()
	{
		//line 9 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.root.AES_Test.__hx_ctor__AES_Test(this);
	}
	
	
	protected static void __hx_ctor__AES_Test(haxe.root.AES_Test __hx_this)
	{
	}
	
	
	public static void test()
	{
		//line 11 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		java.lang.String key1 = haxe.root.Random.string(64, null);
		//line 12 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		java.lang.String iv1 = haxe.root.Random.string(32, null);
		//line 13 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		java.lang.String content = "123789";
		//line 14 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		java.lang.String eKey = haxe.root.AES_Test.encrypt(content, key1, iv1);
		//line 16 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "before=" + eKey ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"AES_Test", "src/AES_Test.hx", "test"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (16) )) )}));
		//line 18 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		java.lang.String data2 = haxe.root.AES_Test.decrypt(eKey, key1, iv1);
		//line 20 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "after=" + data2 ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"AES_Test", "src/AES_Test.hx", "test"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (20) )) )}));
	}
	
	
	public static java.lang.String encrypt(java.lang.String content, java.lang.String key, java.lang.String iv)
	{
		//line 24 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.crypto.Aes aes = new haxe.crypto.Aes(null, null);
		//line 25 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes key1 = haxe.io.Bytes.ofHex(key);
		//line 26 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes text = haxe.io.Bytes.ofString(content, null);
		//line 27 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes iv1 = haxe.io.Bytes.ofHex(iv);
		//line 29 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		aes.init(key1, iv1);
		//line 32 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes data = aes.encrypt(haxe.lang.Runtime.toString("ctr"), text, haxe.lang.Runtime.toString("NoPadding"));
		//line 34 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		return data.toHex();
	}
	
	
	public static java.lang.String decrypt(java.lang.String content, java.lang.String key, java.lang.String iv)
	{
		//line 38 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.crypto.Aes aes = new haxe.crypto.Aes(null, null);
		//line 39 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes key1 = haxe.io.Bytes.ofHex(key);
		//line 41 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes iv1 = haxe.io.Bytes.ofHex(iv);
		//line 43 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		aes.init(key1, iv1);
		//line 45 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes to = haxe.io.Bytes.ofHex(content);
		//line 47 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.io.Bytes data = aes.decrypt(haxe.lang.Runtime.toString("ctr"), to, haxe.lang.Runtime.toString("NoPadding"));
		//line 48 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "Decrypted text: " + haxe.root.Std.string(data) ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"AES_Test", "src/AES_Test.hx", "decrypt"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (48) )) )}));
		//line 50 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\AES_Test.hx"
		return data.toString();
	}
	
	
}


