// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		{
			//line 1 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\?"
			haxe.root.Main.main();
		}
	}
	
	public Main(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Main()
	{
		//line 7 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\Main.hx"
		haxe.root.Main.__hx_ctor__Main(this);
	}
	
	
	protected static void __hx_ctor__Main(haxe.root.Main __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 30 "D:\\Downloads\\Compressed\\heaps-master\\heaps-master\\src\\Main.hx"
		haxe.root.AES_Test.test();
	}
	
	
}


