// Generated by Haxe 4.0.0-rc.5+b1fb4afca
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Random extends haxe.lang.HxObject
{
	public Random(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Random()
	{
		//line 12 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
		haxe.root.Random.__hx_ctor__Random(this);
	}
	
	
	protected static void __hx_ctor__Random(haxe.root.Random __hx_this)
	{
	}
	
	
	public static java.lang.String string(int length, java.lang.String charactersToUse)
	{
		//line 35 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
		if (( charactersToUse == null )) 
		{
			//line 35 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
			charactersToUse = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
		}
		
		//line 36 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
		java.lang.String str = "";
		//line 37 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
		{
			//line 37 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
			int _g = 0;
			//line 37 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
			int _g1 = length;
			//line 37 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
			while (( _g < _g1 ))
			{
				//line 37 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
				int i = _g++;
				//line 39 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
				str += haxe.lang.StringExt.charAt(charactersToUse, ((int) (java.lang.Math.floor(( (( ( charactersToUse.length() - 1 ) + 1 )) * java.lang.Math.random() ))) ));
			}
			
		}
		
		//line 41 "C:\\HaxeToolkit\\haxe\\lib\\random\\1,4,1\\src\\Random.hx"
		return str;
	}
	
	
}


